# Molecule and Atom Introduction

This tutorial is meant to illustrate some of the properties and functionality available within the `Molecule` class. Individual pieces of the molecule can be called and operated on, or the molecule can be operated on as a whole. Let's start with understanding how to work with some of the properties of a molecule.

In [1]:
# Imports necessary packages and checks the version of molli.
import molli as ml 
ml.aux.assert_molli_version_min("1.0a")

## Molecule

A `Molecule` can be loaded in very quickly via a file path or available string. 

In [2]:
#Loads in a molecule
mol1 = ml.load(ml.files.dendrobine_mol2)
mol1

Molecule(name='dendrobine', formula='C16 H25 N1 O2')

An existing `Molecule` object can be quickly copied as is and coordinates can be quickly manipulated and combined. The below example illustrate

In [3]:
#This makes a copy of the original Molecule object and all attributes
mol2 = ml.Molecule(mol1)

#This translates the copy 50 units in the x axis
mol2.translate([50,0,0])

#This creates a new molecule that combines the original molecule and the new molecule.
print((mol1 | mol2).dumps_xyz())

88
unknown
N         1.296000    -0.231900     1.267000
C         0.057300    -0.022600     2.122700
C        -1.097400    -0.473800     1.205900
C        -0.428400    -0.411300    -0.168700
C         0.868300     0.359800    -0.000400
C         2.456200     0.441700     1.836100
C        -2.432800     0.265900     0.983200
C        -2.655300     0.247200    -0.580100
C        -1.242800     0.562600    -1.016300
C         1.535300     0.579000    -1.417900
O         1.341000     2.036300    -1.650700
C         0.078200     2.229100    -2.216600
C        -0.597700     0.853900    -2.402000
O        -0.413500     3.318000    -2.455200
C         0.760200     0.167800    -2.700100
C         0.781200    -1.214100    -3.377300
H         1.242600     0.768400    -3.498200
H        -1.179400     1.558000    -0.537700
H         0.651600     1.395200     0.317400
H        -1.372200    -1.491000     1.513400
C        -0.282800    -1.883500    -0.595700
C         2.177500    -1.841200    -3.321500

Each `Molecule` object is made up of a few key properties

* A `list` of `Atom` objects
* A `list` of `Bond` objects
* A `numpy` array of XYZ (3D) coordinates of atoms
* A `dict` of attributes

In [4]:
print(f'Here are the list of atoms\n{mol1.atoms}\n')
print(f'Here are the list of bonds\n{mol1.bonds}')
print(f'Here are the coordinates of the atoms\n{mol1.coords}')
print(f'Here are the empty dictionary of attributes\n{mol1.attrib}')

Here are the list of atoms
[Atom(element=N, isotope=None, label='N', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=O, isotope=None, label='O', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0), Atom(eleme

## Atom class

Individual atoms can be retrieved in a few different ways from the molecule:


Atoms can be achieved via an index

In [5]:
ex_atom1 = mol1.get_atom(2)
ex_atom1

Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0)

Atoms can be retrieved via an element

In [6]:
ex_atom2 = mol1.get_atom(ml.Element.N)
ex_atom2

Atom(element=N, isotope=None, label='N', formal_charge=0, formal_spin=0)

Atoms can also be retrieved via an assigned label

In [7]:
ex_atom2.label = "Important"
ex_atom3 = mol1.get_atom("Important")
print(f'Example atom 3: {ex_atom3}')
print(f'Is example atom 2 = example atom 3? --> {ex_atom2 == ex_atom3}')

Example atom 3: Atom(element=N, isotope=None, label='Important', formal_charge=0, formal_spin=0)
Is example atom 2 = example atom 3? --> True


Atoms also have a few other important properties

In [8]:
ex_atom2.as_dict()

{'element': N,
 'isotope': None,
 'label': 'Important',
 'atype': <AtomType.sp3: 31>,
 'stereo': <AtomStereo.Unknown: 0>,
 'geom': <AtomGeom.Unknown: 0>,
 'formal_charge': 0,
 'formal_spin': 0,
 'attrib': {},
 '_parent': <weakref at 0x7f9a5bfac900; to 'Molecule' at 0x7f99bb853d10>}

Some other important functionality exists to allow quick retrieval of atoms and information regarding atoms.

This example retrieves a tuple of atoms

In [9]:
atoms_of_interest = mol1.get_atoms(7,8,9,10)
atoms_of_interest

(Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=O, isotope=None, label='O', formal_charge=0, formal_spin=0))

This example retrieves all atoms that are carbon

In [10]:
all_carbon_atoms = mol1.get_atoms(*mol1.yield_atoms_by_element(ml.Element.C))
all_carbon_atoms

(Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=None, label='C', formal_charge=0, formal_spin=0),
 Atom(element=C, isotope=

This example retrieves all atoms that contain the label "Important"

In [11]:
mol1.get_atoms(*mol1.yield_atoms_by_label("Important"))

(Atom(element=N, isotope=None, label='Important', formal_charge=0, formal_spin=0),)

This retrieves the index of an atom

In [12]:
mol1.get_atom_index(ex_atom2)

0

This retrieves the indices of atoms of interest

In [13]:
mol1.get_atom_indices(*atoms_of_interest)

(7, 8, 9, 10)

In addition, atoms can be instantiated entirely independently of a `Molecule` object

In [14]:
# Assigns Silicon to both a and b, but with different geometries and atom types
a = ml.Atom("Si", isotope=29, geom=ml.AtomGeom.R4_Tetrahedral)
b = ml.Atom("Si", isotope=29, atype=ml.AtomType.AttachmentPoint)
print(a)
b.is_attachment_point

Atom(element=Si, isotope=29, label=None, formal_charge=0, formal_spin=0)


True

The elements of atoms can also be rapidly changed

In [15]:
a.element = 83
a

Atom(element=Bi, isotope=29, label=None, formal_charge=0, formal_spin=0)

Each `Atom` can also be assigned different attributes of common data types within python easily as though it were a dictionary.

In [16]:
print(f'Current attribute list for Example Atom A')
a.attrib["List"] = [0,1,2]
a.attrib["Tuple"] = ('a','b','c')
a.attrib["Dictionary"] = {"Data": (0.1, 0.2, 0.3)}

a.attrib

Current attribute list for Example Atom A


{'List': [0, 1, 2],
 'Tuple': ('a', 'b', 'c'),
 'Dictionary': {'Data': (0.1, 0.2, 0.3)}}

Coordinates of atoms or sets of atoms can quickly be retrieved from their associated atoms

In [17]:
atom2_coord = mol1.get_atom_coord(ex_atom1)
print(f'Example Atom 2 Coordinates: {atom2_coord}')

all_carbon_subset = mol1.coord_subset(all_carbon_atoms)
print(f'All Carbon Atom subset:\n{all_carbon_subset}')

Example Atom 2 Coordinates: [-1.0974 -0.4738  1.2059]
All Carbon Atom subset:
[[ 5.7300e-02 -2.2600e-02  2.1227e+00]
 [-1.0974e+00 -4.7380e-01  1.2059e+00]
 [-4.2840e-01 -4.1130e-01 -1.6870e-01]
 [ 8.6830e-01  3.5980e-01 -4.0000e-04]
 [ 2.4562e+00  4.4170e-01  1.8361e+00]
 [-2.4328e+00  2.6590e-01  9.8320e-01]
 [-2.6553e+00  2.4720e-01 -5.8010e-01]
 [-1.2428e+00  5.6260e-01 -1.0163e+00]
 [ 1.5353e+00  5.7900e-01 -1.4179e+00]
 [ 7.8200e-02  2.2291e+00 -2.2166e+00]
 [-5.9770e-01  8.5390e-01 -2.4020e+00]
 [ 7.6020e-01  1.6780e-01 -2.7001e+00]
 [ 7.8120e-01 -1.2141e+00 -3.3773e+00]
 [-2.8280e-01 -1.8835e+00 -5.9570e-01]
 [ 2.1775e+00 -1.8412e+00 -3.3215e+00]
 [ 3.4850e-01 -1.1006e+00 -4.8514e+00]]
